"""initial models

Revision ID: c264e13de148
Revises: 
Create Date: 2026-09-19 18:34:02.652463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c264e13de148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('picked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reading_start_date', sa.Date(), nullable=True),
    sa.Column('reading_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('TO_BE_READ', 'CURRENTLY_READING', 'FINISHED', 'ABANDONED', name='bookstatus'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['picked_by_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('score >= 1.0 AND score <= 5.0 AND (score * 2) = CAST(score * 2 AS INTEGER)', name='score_range'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'member_id', name='one_review_per_member_per_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('book')
    op.drop_table('member')
    # ### end Alembic commands ###
